language: rust

addons:
  apt:
    packages:
      - libssl-dev

install:
  - ./scripts/install-tarpaulin.sh

script:
  - cargo tarpaulin -v --ciserver travis-ci --coveralls $TRAVIS_JOB_ID --all-features
