[package]
name = "kafi-kässeli"
version = "0.1.0"
authors = ["Jeremy Stucki <jeremy@myelin.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
